export const movies = [
    {
        img: "https://img.youtube.com/vi/U1syO2g_qjw/sddefault.jpg",
        title: "Como elaborar um currículo profissional de impacto",
        link: "https://www.youtube.com/embed/U1syO2g_qjw",
        category: "Diversos",
        featuread: true,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/U1syO2g_qjw?si=hjHCJuCHHQPYBPX-" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        "img": "https://img.youtube.com/vi/1LzD5zkgQKo/sddefault.jpg",
        "title": "Descomplicando o Front‑End: Segredos para Criar Interfaces que Funcionam",
        "link": "https://www.youtube.com/embed/1LzD5zkgQKo",
        "category": "Diversos",
        "featuread": false,
        "iframe": "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/1LzD5zkgQKo\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>"
    },

    {
        "img": "https://img.youtube.com/vi/393aD8C6dS8/sddefault.jpg",
        "title": "Técnicas Avançadas de Prompts de IA Generativa para Profissionais de TI | Webinar Completo",
        "link": "https://www.youtube.com/embed/393aD8C6dS8",
        "category": "Diversos",
        "featuread": false,
        "iframe": "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/393aD8C6dS8\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>"
    },

    {
        "img": "https://img.youtube.com/vi/aDjAUFUTBsw/sddefault.jpg",
        "title": "Autopercepção – O caminho para uma carreira alinhada aos seus valores",
        "link": "https://www.youtube.com/embed/aDjAUFUTBsw",
        "category": "Diversos",
        "featuread": false,
        "iframe": "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/aDjAUFUTBsw\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>"
    },

    {
        img: "https://img.youtube.com/vi/GPTGoaHndrU/sddefault.jpg",
        title: "Componentização e Boas práticas em React",
        link: "https://www.youtube.com/embed/GPTGoaHndrU",
        category: "Diversos",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/GPTGoaHndrU?si=PcalRLw0EWfdrGIj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },

    {
        img: "https://img.youtube.com/vi/1YkwNNuIJFI/sddefault.jpg",
        title: "Do IF/ELSE ao Machine Learning: Uma Nova Forma de Programar",
        link: "https://www.youtube.com/embed/1YkwNNuIJFI",
        category: "Diversos",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/1YkwNNuIJFI?si=USiPl1H9pKlzAbuU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },

    {
        img: "https://img.youtube.com/vi/SJb_MNOYJbE/sddefault.jpg",
        title: "Do Zero a Desenvolvedor Web Full Stack - Contratado em 6 meses",
        link: "https://www.youtube.com/embed/SJb_MNOYJbE",
        category: "Diversos",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/SJb_MNOYJbE?si=iqT2nFC4UpjhyHnI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },

    {
        img: "https://img.youtube.com/vi/XTBZ2jWh7Gs/sddefault.jpg",
        title: "Transição de Carreira, Formação e Contratação: A Jornada de Thobias Silva na Tecnologia",
        link: "https://www.youtube.com/embed/XTBZ2jWh7Gs",
        category: "Diversos",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/XTBZ2jWh7Gs?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },

    //webinar flutter
    {
        img: "https://img.youtube.com/vi/WKbLXuP9S-c/sddefault.jpg",
        title: "Webinar - Recriando a interface do Linkedin com Flutter",
        link: "https://www.youtube.com/embed/WKbLXuP9S-c",
        category: "Webinar em Flutter",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/WKbLXuP9S-c?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/dJ6y1zMjVXU/sddefault.jpg",
        title: "Webinar - Recriando a interface do Instagram com Flutter",
        link: "https://www.youtube.com/embed/dJ6y1zMjVXU",
        category: "Webinar em Flutter",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/dJ6y1zMjVXU?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/8rdJsqUjsGg/sddefault.jpg",
        title: "Webinar - Recriando a interface do iFood com Flutter",
        link: "https://www.youtube.com/embed/8rdJsqUjsGg",
        category: "Webinar em Flutter",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/8rdJsqUjsGg?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/C4p_7qBsECw/sddefault.jpg",
        title: "Webinar - Recriando a interface do PicPay com Flutter",
        link: "https://www.youtube.com/embed/C4p_7qBsECw",
        category: "Webinar em Flutter",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/C4p_7qBsECw?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/L1pKoMC6hWk/sddefault.jpg",
        title: "Webinar - Recriando o layout do WhatsApp com Flutter",
        link: "https://www.youtube.com/embed/L1pKoMC6hWk",
        category: "Webinar em Flutter",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/L1pKoMC6hWk?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },

    //Jornada UX/UI

    {
        img: "https://img.youtube.com/vi/FiZMowbaiJA/sddefault.jpg",
        title: "Live #5 Jornada UX/UI: O UX/UI Design é para todos?",
        link: "https://www.youtube.com/embed/FiZMowbaiJA",
        category: "Jornada UX/UI",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/FiZMowbaiJA?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/cwqDu0ZzbYE/sddefault.jpg",
        title: "Live #4 Jornada UX/UI: Como migrar para o UX/UI Design: a trajetória de uma designer - Growdev",
        link: "https://www.youtube.com/embed/cwqDu0ZzbYE",
        category: "Jornada UX/UI",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/cwqDu0ZzbYE?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/ZMZjQ9aRuIY/sddefault.jpg",
        title: "Live #3 Jornada UX/UI: As oportunidades de estudar um programa de formação pagando após formado",
        link: "https://www.youtube.com/embed/ZMZjQ9aRuIY",
        category: "Jornada UX/UI",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/ZMZjQ9aRuIY?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/8sd3wuKTZMA/sddefault.jpg",
        title: "Live #2 Jornada UX/UI: O profissional de UX/UI Design no mercado digital - Growdev",
        link: "https://www.youtube.com/embed/8sd3wuKTZMA",
        category: "Jornada UX/UI",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/8sd3wuKTZMA?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/-26aqPtgoEY/sddefault.jpg",
        title: "Live #1 Jornada UX/UI: O papel do UX/UI Designer no desenvolvimento de um produto digital - Growdev",
        link: "https://www.youtube.com/embed/-26aqPtgoEY",
        category: "Jornada UX/UI",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/-26aqPtgoEY?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },

    //Growcast [Episódios]
    {
        img: "https://img.youtube.com/vi/aJ-HZuLcKeA/sddefault.jpg",
        title: "Growcast #00 | Conheça a Growdev",
        link: "https://www.youtube.com/embed/aJ-HZuLcKeA",
        category: "Growcast [Episódios]",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/aJ-HZuLcKeA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/7OWT3lfHYvE/sddefault.jpg",
        title: "Growcast #01 | As profissões do futuro",
        link: "https://www.youtube.com/embed/7OWT3lfHYvE",
        category: "Growcast [Episódios]",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/7OWT3lfHYvE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/ci1eQGPK89o/sddefault.jpg",
        title: "Growcast #02 | Como seguir a carreira internacional?",
        link: "https://www.youtube.com/embed/ci1eQGPK89o",
        category: "Growcast [Episódios]",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/ci1eQGPK89o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/WM7pGG7OicQ/sddefault.jpg",
        title: "Growcast #04 | Agile Master: tudo sobre a profissão!",
        link: "https://www.youtube.com/embed/WM7pGG7OicQ",
        category: "Growcast [Episódios]",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/WM7pGG7OicQ?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/2c8VOBZ160Y/sddefault.jpg",
        title: "Growcast #5 | Como iniciar na carreira em Desenvolvimento de Softwares?",
        link: "https://www.youtube.com/embed/2c8VOBZ160Y",
        category: "Growcast [Episódios]",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/2c8VOBZ160Y?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/mxnEm03cYPc/sddefault.jpg",
        title: "Growcast #06 | Mulheres e inclusão na tecnologia",
        link: "https://www.youtube.com/embed/mxnEm03cYPc",
        category: "Growcast [Episódios]",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/mxnEm03cYPc?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/m7DyR07KrOE/sddefault.jpg",
        title: "Growcast #07 | Desenvolvendo profissionais na área de TI",
        link: "https://www.youtube.com/embed/m7DyR07KrOE",
        category: "Growcast [Episódios]",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/m7DyR07KrOE?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/vW8G9KPwRL0/sddefault.jpg",
        title: "Growcast #8 | A solução que está transformando o mercado de TI no Brasil",
        link: "https://www.youtube.com/embed/vW8G9KPwRL0",
        category: "Growcast [Episódios]",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/vW8G9KPwRL0?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/vW8G9KPwRL0/sddefault.jpg",
        title: "Growcast #9 | Acompanhe com quem realmente entende, tudo sobre o mercado de trabalho no mundo da TI.",
        link: "https://www.youtube.com/embed/vW8G9KPwRL0",
        category: "Growcast [Episódios]",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/vW8G9KPwRL0?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/_Ut2KqAqPyk/sddefault.jpg",
        title: "Growcast #10 | Mobile: Um mercado que cresce muito e está transformando vidas.",
        link: "https://www.youtube.com/embed/_Ut2KqAqPyk",
        category: "Growcast [Episódios]",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/_Ut2KqAqPyk?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/VOvngm1kTzg/sddefault.jpg",
        title: "Growcast #11 | A inteligência por trás dos Dados com Murilo Jovtei - Arezzo & CO",
        link: "https://www.youtube.com/embed/VOvngm1kTzg",
        category: "Growcast [Episódios]",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/VOvngm1kTzg?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/DfVhbfbubAE/sddefault.jpg",
        title: "Growcast #12 | Tecnologia Mobile com Laercio Konzen, Desenvolvedor React Native na Arezzo & CO",
        link: "https://www.youtube.com/embed/DfVhbfbubAE",
        category: "Growcast [Episódios]",
        featuread: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/DfVhbfbubAE?si=h-HMmp5Bn5Ex-M3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
];